# Generated by Django 5.2.5 on 2025-08-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'В ожидании'), ('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка'), ('TIMEOUT', 'Тайм-аут')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('code', models.TextField(verbose_name='Исходный код')),
                ('stdout', models.TextField(blank=True, null=True, verbose_name='Стандартный вывод (stdout)')),
                ('stderr', models.TextField(blank=True, null=True, verbose_name='Стандартная ошибка (stderr)')),
                ('error_context', models.JSONField(blank=True, help_text='Сохраняет детали проваленного теста (input, expected, actual).', null=True, verbose_name='Контекст ошибки')),
                ('ai_suggestion', models.TextField(blank=True, null=True, verbose_name='Рекомендация от AI')),
                ('ai_response_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время ответа AI (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Проверка кода',
                'verbose_name_plural': 'Проверки кода',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommonError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_pattern', models.CharField(help_text='Регулярное выражение для поиска в stderr.', max_length=255, unique=True, verbose_name='Шаблон ошибки (regex)')),
                ('title', models.CharField(max_length=255, verbose_name='Причина ошибки')),
                ('description', models.TextField(verbose_name='Описание и решение')),
            ],
            options={
                'verbose_name': 'Типовая ошибка',
                'verbose_name_plural': 'Реестр типовых ошибок',
            },
        ),
    ]
