# Generated by Django 5.2.5 on 2025-08-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checker', '0001_initial'),
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='courses.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='check',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='users.user', verbose_name='Пользователь'),
        ),
    ]
