# Generated by Django 5.2.5 on 2025-08-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonError',
        ),
    ]
