# Generated by Django 5.2.5 on 2025-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Краткий текст вопроса.', max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Полный текст ответа.', verbose_name='Ответ')),
                ('media_file', models.FileField(blank=True, help_text='Опциональный файл для отправки (фото, видео, документ, аудио).', null=True, upload_to='faq_media/', verbose_name='Медиафайл')),
                ('media_type', models.CharField(blank=True, choices=[('PHOTO', 'Фото'), ('VIDEO', 'Видео'), ('DOCUMENT', 'Документ'), ('AUDIO', 'Аудио')], help_text='Необходимо указать тип, если вы прикрепили медиафайл.', max_length=10, null=True, verbose_name='Тип медиафайла')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке будет вопрос.', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_link', models.URLField(default='https://t.me/your_support_username', help_text='URL-адрес на чат поддержки.', verbose_name='Ссылка на тех. поддержку')),
            ],
            options={
                'verbose_name': 'Тех. поддержка',
                'verbose_name_plural': 'Тех. поддержка',
            },
        ),
    ]
