# Generated by Django 5.2.5 on 2025-08-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottexts',
            name='ai_analysis_message',
            field=models.CharField(default='🤖 Анализирую ваше решение... Это может занять несколько минут', max_length=255, verbose_name='Сообщение об анализе AI'),
        ),
        migrations.AddField(
            model_name='bottexts',
            name='choose_course_message',
            field=models.CharField(default='Выберите курс:', max_length=255, verbose_name='Заголовок выбора курса'),
        ),
        migrations.AddField(
            model_name='bottexts',
            name='choose_level_message',
            field=models.CharField(default='Выберите уровень сложности:', max_length=255, verbose_name='Заголовок выбора уровня'),
        ),
        migrations.AddField(
            model_name='bottexts',
            name='choose_module_message',
            field=models.CharField(default='Выберите модуль:', max_length=255, verbose_name='Заголовок выбора модуля'),
        ),
        migrations.AddField(
            model_name='bottexts',
            name='choose_task_message',
            field=models.CharField(default='Выберите задачу:', max_length=255, verbose_name='Заголовок выбора задачи'),
        ),
        migrations.AddField(
            model_name='bottexts',
            name='no_courses_available_message',
            field=models.CharField(default='У вас пока нет доступных курсов.', max_length=255, verbose_name='Сообщение об отсутствии курсов'),
        ),
    ]
