# Generated by Django 5.2.5 on 2025-08-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField(default='Привет! Я бот для проверки python-кода. Отправь мне свой код, и я скажу, есть ли в нем ошибки и как их решить.', help_text='Отображается после успешной авторизации.', verbose_name='Приветственное сообщение')),
                ('request_contact_message', models.TextField(default='Здравствуйте! Для использования бота, пожалуйста, подтвердите свой номер телефона.', help_text='Первое сообщение пользователю при команде /start, если он не авторизован.', verbose_name='Запрос номера телефона')),
                ('already_authorized_message', models.TextField(default='Вы уже авторизованы.', help_text='Когда пользователь с контактом пытается снова отправить контакт.', verbose_name='Сообщение для уже авторизованных')),
                ('whitelist_success_message', models.TextField(default='Ваш номер подтвержден и есть в списке. Добро пожаловать!', help_text='Сообщение после успешной сверки номера с белым списком.', verbose_name='Успешная проверка в белом списке')),
                ('whitelist_fail_message', models.TextField(default='К сожалению, вашего номера нет в белом списке. Доступ запрещен.', help_text='Сообщение, если номера пользователя нет в белом списке.', verbose_name='Неуспешная проверка в белом списке')),
                ('main_menu_message', models.TextField(default='Вы в главном меню.', help_text='Текст, который видит пользователь в главном меню.', verbose_name='Сообщение главного меню')),
                ('menu_return_message', models.TextField(default='Вы вернулись в главное меню.', help_text="Отображается при нажатии на кнопку 'Вернуться в меню'.", verbose_name='Сообщение о возврате в меню')),
                ('request_code_message', models.TextField(default='Отправьте мне свой python-код текстом или файлом (.txt, .py, .docx).', help_text="Сообщение после нажатия кнопки 'Проверить код'.", verbose_name='Запрос кода для проверки')),
                ('code_in_review_message', models.TextField(default='Код получен и отправлен на проверку. Это может занять несколько минут. Ожидайте...', help_text='Сообщение сразу после того, как пользователь отправил код.', verbose_name='Сообщение о принятии кода на проверку')),
                ('faq_list_title', models.TextField(default='Часто задаваемые вопросы:', help_text='Текст, который отображается над списком вопросов в разделе FAQ.', verbose_name='Заголовок списка FAQ')),
            ],
            options={
                'verbose_name': 'Тексты бота',
                'verbose_name_plural': 'Тексты бота',
            },
        ),
    ]
