# Generated by Django 5.2.5 on 2025-08-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_bottexts_ai_analysis_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottexts',
            name='ai_analysis_message',
            field=models.TextField(default='🤖 Анализирую ваше решение... Это может занять несколько минут', help_text="Отображается после нажатия кнопки 'Дать обратную связь на решение'.", verbose_name='Сообщение об анализе AI'),
        ),
        migrations.AlterField(
            model_name='bottexts',
            name='choose_course_message',
            field=models.TextField(default='Выберите курс:', help_text='Заголовок над списком доступных курсов.', verbose_name='Заголовок выбора курса'),
        ),
        migrations.AlterField(
            model_name='bottexts',
            name='choose_level_message',
            field=models.TextField(default='Выберите уровень сложности:', help_text='Заголовок над списком уровней сложности в выбранном модуле.', verbose_name='Заголовок выбора уровня'),
        ),
        migrations.AlterField(
            model_name='bottexts',
            name='choose_module_message',
            field=models.TextField(default='Выберите модуль:', help_text='Заголовок над списком модулей в выбранном курсе.', verbose_name='Заголовок выбора модуля'),
        ),
        migrations.AlterField(
            model_name='bottexts',
            name='choose_task_message',
            field=models.TextField(default='Выберите задачу:', help_text='Заголовок над списком задач в выбранном уровне.', verbose_name='Заголовок выбора задачи'),
        ),
        migrations.AlterField(
            model_name='bottexts',
            name='no_courses_available_message',
            field=models.TextField(default='У вас пока нет доступных курсов.', help_text='Сообщение, если у пользователя нет доступа ни к одному курсу.', verbose_name='Сообщение об отсутствии курсов'),
        ),
        migrations.AlterField(
            model_name='bottexts',
            name='request_code_message',
            field=models.TextField(default='Отправьте мне свой python-код текстом или файлом (.txt, .py, .docx).', help_text="Сообщение после нажатия кнопки 'Решить задачу'.", verbose_name='Запрос кода для проверки'),
        ),
    ]
