services:
  db:
    image: postgres:17-alpine
    container_name: dmentor_db_dev
    volumes:
      - postgres_data_dm_dev:/var/lib/postgresql/data/
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: dmentor_redis_dev
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dm_dev:/data
    env_file:
      - ../.env  
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    container_name: dmentor_backend_dev
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
      - static_volume_dm_dev:/app/backend/static
      - media_volume_dm_dev:/app/backend/media
    expose:
      - 8000
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  bot:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    container_name: dmentor_bot_dev
    command: python bot/main.py
    volumes:
      - ../:/app
      - media_volume_dm_dev:/app/backend/media
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build:
      context: ..
      dockerfile: docker/python.Dockerfile
    container_name: dmentor_celery_worker_dev
    command: celery -A backend.core worker -l INFO
    volumes:
      - ../:/app
      - media_volume_dm_dev:/app/backend/media
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_temp_data_dm_dev:/runner_temp
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.27.5-alpine
    container_name: dmentor_nginx_dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - static_volume_dm_dev:/app/backend/static:ro
      - media_volume_dm_dev:/app/backend/media:ro
    env_file: ../.env
    environment:
      NGINX_PORT: 80
      BACKEND_PORT: 8000
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    depends_on:
      backend:
        condition: service_started
  
volumes:
  postgres_data_dm_dev:
  redis_data_dm_dev:
  static_volume_dm_dev:
  media_volume_dm_dev:
  runner_temp_data_dm_dev:
