# Generated by Django 5.2.5 on 2025-08-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='difficultylevel',
            unique_together={('module', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('level', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='usertaskstatus',
            unique_together={('user', 'task')},
        ),
    ]
