# Generated by Django 5.2.5 on 2025-08-26 16:45

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('checks_count', models.PositiveIntegerField(default=0, verbose_name='Количество проверок кода')),
                ('successful_checks_count', models.PositiveIntegerField(default=0, verbose_name='Успешных проверок')),
                ('failed_checks_count', models.PositiveIntegerField(default=0, verbose_name='Неуспешных проверок')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('courses', models.ManyToManyField(blank=True, help_text='Выберите курсы, к которым будет предоставлен доступ по этому номеру.', related_name='whitelisted_phones', to='courses.course', verbose_name='Доступные курсы')),
            ],
            options={
                'verbose_name': 'Запись в белом списке',
                'verbose_name_plural': 'Белый список',
            },
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
