# Generated by Django 5.2.5 on 2025-08-14 13:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Телеграм ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона')),
                ('checks_count', models.PositiveIntegerField(default=0, verbose_name='Количество проверок кода')),
                ('successful_checks_count', models.PositiveIntegerField(default=0, verbose_name='Успешных проверок')),
                ('failed_checks_count', models.PositiveIntegerField(default=0, verbose_name='Неуспешных проверок')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Белый список',
                'verbose_name_plural': 'Белый список',
            },
        ),
    ]
