# Generated by Django 5.2.5 on 2025-08-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'Запись в белом списке', 'verbose_name_plural': 'Белый список'},
        ),
        migrations.AddField(
            model_name='whitelist',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Выберите курсы, к которым будет предоставлен доступ по этому номеру.', related_name='whitelisted_phones', to='courses.course', verbose_name='Доступные курсы'),
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_accesses', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к курсу',
                'verbose_name_plural': 'Доступы к курсам',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
